### ISSUE TITLE
Thank your job

### ISSUE THREAD

**Issue by autofit** [octavioturra/react-native-alt-beacon#3]
i do a app with your code,thanks share it ...

**Comment by octavioturra** [comment]
Thank you so much, guy. I've release the 1.1.0 version. If you want to take a test, there is a new and better docs too.

**Comment by autofit** [comment]
thanks!

**Comment by autofit** [comment]
Quote error：no sdk,i don't know where sdk for this

FAILURE: Build failed with an exception.

What went wrong: A problem occurred configuring project ':RNABeacon'. > The SDK directory 'F:\rn\afapp\android\Users\octavioturra\android-sdks' does n ot exist.
Failed to build DependencyGraph: @providesModule naming collision:
Duplicate module name: merge
Paths: F:\rn\afapp\android\users\octavioturra\android-sdks\merge\package.json
collides with F:\rn\afapp\node_modules\react-native\Libraries\vendor\core\merge.
js

This error is caused by a @providesModule declaration with the same name accross
two different files.
Error: @providesModule naming collision:
Duplicate module name: merge
Paths: F:\rn\afapp\android\users\octavioturra\android-sdks\merge\package.json

**Comment by andrekovac** [comment]
@autofit : My pull-request #6 should solve the sdk issue when running the example. Give it a try.

**Comment by autofit** [comment]
@Andruschenko Thank you:)

**Comment by autofit** [comment]
example demo no run,.babelrc:{
  "presets": [ "react-native-stage-0/decorator-support" ]
} error -->

F:\rn\afapp>react-native start
F:\rn\afapp\node_modules\babel-core\lib\transformation\file\options\option-manag
er.js:372
          throw new Error("Couldn't find preset " + JSON.stringify(val) + " rela
tive to directory " + JSON.stringify(dirname));
          ^

Error: Couldn't find preset "react-native-stage-0/decorator-support" relative to
 directory "F:\\rn\\afapp"
    at F:\rn\afapp\node_modules\babel-core\lib\transformation\file\options\optio
n-manager.js:372:17
    at Array.map (native)
    at OptionManager.resolvePresets (F:\rn\afapp\node_modules\babel-core\lib\tra
nsformation\file\options\option-manager.js:364:20)
    at OptionManager.mergePresets (F:\rn\afapp\node_modules\babel-core\lib\trans
formation\file\options\option-manager.js:348:10)
    at OptionManager.mergeOptions (F:\rn\afapp\node_modules\babel-core\lib\trans
formation\file\options\option-manager.js:307:14)
    at OptionManager.addConfig (F:\rn\afapp\node_modules\babel-core\lib\transfor
mation\file\options\option-manager.js:207:10)
    at OptionManager.findConfigs (F:\rn\afapp\node_modules\babel-core\lib\transf
ormation\file\options\option-manager.js:413:16)
    at OptionManager.init (F:\rn\afapp\node_modules\babel-core\lib\transformatio
n\file\options\option-manager.js:461:12)
    at compile (F:\rn\afapp\node_modules\babel-register\lib\node.js:81:45)
    at loader (F:\rn\afapp\node_modules\babel-register\lib\node.js:126:14)
